workflows:
  flutter-app:
    name: Build Android APK & iOS
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com

  ios-release:
    name: iOS Release to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.martinjon.taoapp"
        APPLE_ID: "$APPLE_ID"  # ← Add this line
        APP_SPECIFIC_PASSWORD: "$APP_SPECIFIC_PASSWORD"  # ← Add this line
    scripts:
      - name: List available certificates
        script: |
          keychain initialize
          echo "=== Available Signing Certificates ==="
          security find-identity -v -p codesigning
          echo "=== End Certificate List ==="
      - name: Build iOS for App Store
        script: |
          flutter build ipa --release
    publishing:
      app_store_connect:
        username: "$APPLE_ID"
        password: "$APP_SPECIFIC_PASSWORD"
        submit_to_testflight: true
      email:
        recipients:
          - mjongarcia@gmail.com
