workflows:
#
#   android-release:
#     name: Android Release (with underscore)
#     environment:
#       groups:
#         - android_signing
#       flutter: stable
#     scripts:
#       - name: Build Android with underscore
#         script: |
#           flutter clean
#           flutter pub get
#           echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
#           ls -la android/app/upload-keystore.jks
#           echo "Keystore file created successfully"
#           flutter build appbundle --release
#     artifacts:
#       - build/app/outputs/bundle/release/app-release.aab
#     publishing:
#       email:
#         recipients:
#           - mjongarcia@gmail.com

  # iOS workflow
  
    ios-release:
      name: iOS Release
      environment:
        flutter: stable
        xcode: latest
        cocoapods: default
      scripts:
        - name: Build iOS with Debug
          script: |
            flutter clean
            flutter pub get
            echo "=== Starting build - this might trigger certificate setup ==="
            flutter build ipa --release --verbose
      artifacts:
        - build/ios/ipa/
      publishing:
        email:
          recipients:
            - mjongarcia@gmail.com
