workflows:
  android-release:
    name: Android Release (with underscore)
    environment:
      groups:
        - android_signing
      flutter: stable
    scripts:
      - name: Build Android with underscore
        script: |
          flutter clean
          flutter pub get
          echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
          ls -la android/app/upload-keystore.jks
          echo "Keystore file created successfully"
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com

#   COMMENT OUT OR REMOVE THE iOS WORKFLOW
  ios-release:
    name: iOS Release - Manual Signing
    instance_type: mac_mini_m2
    environment:
      groups:
        - ios_signing
        - app_store_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up signing files
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision
          
          # Install certificate
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain
          security import /tmp/certificate.p12 -k build.keychain -P $CM_CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          
          # Install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(grep -a -A 1 UUID /tmp/profile.mobileprovision | grep string | sed 's/<string>//;s/<\/string>//' | tr -d '\t ')
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
          
      - name: Configure Xcode for manual signing
        script: |
          # Get certificate name
          CERT_NAME=$(security find-identity -v -p codesigning build.keychain | head -1 | grep -o '".*"' | tr -d '"')
          
          # Get profile UUID
          PROFILE_UUID=$(grep -a -A 1 UUID ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | grep string | sed 's/<string>//;s/<\/string>//' | tr -d '\t ')
          
          # Configure Xcode project for manual signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = ZNJH9AA2CY;/" ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/\"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]\" = \"iPhone Developer\";/\"CODE_SIGN_IDENTITY[sdk=iphoneos*]\" = \"$CERT_NAME\";/" ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = \"\";/PROVISIONING_PROFILE_SPECIFIER = \"$PROFILE_UUID\";/" ios/Runner.xcodeproj/project.pbxproj
          
      - name: Build iOS
        script: |
          flutter pub get
          flutter build ipa --release
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mjongarcia@gmail.com
