# workflows:
#   flutter-app:
#     name: Build Android APK & iOS
#     environment:
#       flutter: stable
#     scripts:
#       - name: Get packages
#         script: flutter pub get
#       - name: Build Android APK
#         script: flutter build apk --release
#       - name: Build iOS
#         script: flutter build ipa --release
#     artifacts:
#       - build/app/outputs/flutter-apk/app-release.apk
#       - build/ios/ipa/*.ipa
#     publishing:
#       email:
#         recipients:
#           - mjongarcia@gmail.com

workflows:
  ios-release:
    name: iOS Release to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing certificates
        script: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --type IOS_APP_STORE --create
      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Show certificates
        script: |
          echo "=== Available Certificates ==="
          security find-identity -v -p codesigning
      - name: Build iOS
        script: |
          flutter pub get
          flutter build ipa --release --no-codesign
      - name: Code sign manually
        script: |
          cd build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportOptionsPlist ../../ios/Runner/ExportOptions.plist \
            -exportPath . \
            -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mjongarcia@gmail.com
