workflows:
#
#   android-release:
#     name: Android Release (with underscore)
#     environment:
#       groups:
#         - android_signing
#       flutter: stable
#     scripts:
#       - name: Build Android with underscore
#         script: |
#           flutter clean
#           flutter pub get
#           echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
#           ls -la android/app/upload-keystore.jks
#           echo "Keystore file created successfully"
#           flutter build appbundle --release
#     artifacts:
#       - build/app/outputs/bundle/release/app-release.aab
#     publishing:
#       email:
#         recipients:
#           - mjongarcia@gmail.com

  # iOS workflow
  ios-release:
    name: iOS Release (no underscore)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Debug ALL Environment Variables
        script: |  # ← NO DASH here!
          echo "=== ALL ENVIRONMENT VARIABLES ==="
          env
          echo "=== END ==="
      - name: Debug Environment Variables
        script: |  # ← NO DASH here!
          echo "=== DEBUGGING ENV VARS ==="
          env | grep APP_STORE
          echo "=== END DEBUG ==="
      - name: Setup Code Signing
        script: |  # ← NO DASH here!
          echo "Debug - Checking environment variables:"
          echo "ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "KEY_ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo "PRIVATE_KEY length: ${#APP_STORE_CONNECT_PRIVATE_KEY}"
          keychain initialize
          app-store-connect fetch-signing-files "com.martinjon.taoapp" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key="$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS without underscore
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release
    artifacts: # ← This should be at SAME level as "scripts" and "environment"
      - build/ios/ipa/*.ipa
    publishing: # ← This should be at SAME level as "scripts" and "environment"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mjongarcia@gmail.com
