workflows:
#
#   android-release:
#     name: Android Release (with underscore)
#     environment:
#       groups:
#         - android_signing
#       flutter: stable
#     scripts:
#       - name: Build Android with underscore
#         script: |
#           flutter clean
#           flutter pub get
#           echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
#           ls -la android/app/upload-keystore.jks
#           echo "Keystore file created successfully"
#           flutter build appbundle --release
#     artifacts:
#       - build/app/outputs/bundle/release/app-release.aab
#     publishing:
#       email:
#         recipients:
#           - mjongarcia@gmail.com

  # iOS workflow

  ios-release:
    name: iOS Release - Find Artifact
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build and Locate IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --export-method ad-hoc
          echo "=== SEARCHING FOR IPA FILES ==="
          find . -name "*.ipa" -type f 2>/dev/null || echo "No IPA files found"
          echo "=== CHECKING BUILD DIRECTORIES ==="
          ls -la build/ || echo "No build directory"
          ls -la build/ios/ || echo "No ios build directory"
    artifacts:
      - build/ios/ipa/
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com
