workflows:
  android-release:
    name: Android Release (with underscore)
    environment:
      groups:
        - android_signing
      flutter: stable
    scripts:
      - name: Build Android with underscore
        script: |
          flutter clean
          flutter pub get
          echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
          ls -la android/app/upload-keystore.jks
          echo "Keystore file created successfully"
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com

#   COMMENT OUT OR REMOVE THE iOS WORKFLOW
  ios-release:
     name: iOS Release - Auto Signing
     instance_type: mac_mini_m2
     environment:
       flutter: stable
       groups:
         - app_store_credentials
       xcode: latest
       cocoapods: default
     scripts:
#       - name: Set up code signing
#         script: |
#           app-store-connect fetch-signing-files com.martinjon.taoapp \
#           --type IOS_APP_STORE \
#           --certificate-key=@env:CERTIFICATE_PRIVATE_KEY \
#           --create
       - name: Set up Keychain
         script: |
           keychain initialize
       - name: Build iOS
         script: |
           flutter clean
           flutter pub get
           xcode-project build-ipa \
             --workspace "ios/Runner.xcworkspace" \
             --scheme "Runner" \
             --archive-flags="-allowProvisioningUpdates"
     publishing:
       app_store_connect:
         api_key: $APP_STORE_CONNECT_PRIVATE_KEY
         key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
         issuer_id: $APP_STORE_CONNECT_ISSUER_ID
         submit_to_testflight: true
       email:
         recipients:
           - mjongarcia@gmail.com
