workflows:
  android-release:
    name: Android Release (with underscore)
    environment:
      groups:
        - android_signing
      flutter: stable
    scripts:
      - name: Build Android with underscore
        script: |
          flutter clean
          flutter pub get
          echo $CM_KEYSTORE | base64 --decode > android/app/upload-keystore.jks
          ls -la android/app/upload-keystore.jks
          echo "Keystore file created successfully"
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com

#   COMMENT OUT OR REMOVE THE iOS WORKFLOW
  ios-release:
    name: iOS Release - Auto Signing
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files com.martinjon.taoapp \
            --type IOS_APP_STORE \
            --create
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Build iOS
        script: |
          xcode-project use-profiles
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mjongarcia@gmail.com
