workflows:
  # Android with underscore
  android-release:
    name: Android Release (with underscore)
    environment:
      flutter: stable
    scripts:
      - name: Build Android with underscore
        script: |
          flutter clean
          flutter pub get
          # Build with underscore package name
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - mjongarcia@gmail.com

#  # iOS without underscore
#  ios-release:
#    name: iOS Release (no underscore)
#    environment:
#      flutter: stable
#      xcode: latest
#      cocoapods: default
#      groups:
#        - app_store_credentials
#    scripts:
#      - name: Setup Code Signing
#        script: |
#          keychain initialize
#          app-store-connect fetch-signing-files "com.martinjon.taoapp" --type IOS_APP_STORE --create
#          keychain add-certificates
#          xcode-project use-profiles
#      - name: Build iOS without underscore
#        script: |
#          flutter clean
#          flutter pub get
#          flutter build ipa --release
#    artifacts:
#      - build/ios/ipa/*.ipa
#    publishing:
#      app_store_connect:
#        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
#        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
#        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
#        submit_to_testflight: true
#      email:
#        recipients:
#          - mjongarcia@gmail.com
